In [9]:
import pandas as pd


print(pd.DataFrame([1,2,3,4,5]))

   0
0  1
1  2
2  3
3  4
4  5

# ejercicio 1:Filtrado y agrupacion de datos con Pandas.

Dispones de un conjuntos de datos de ventas mensuales de distintos empleados, tu objetivo es :
    1- Filtrar un dataframe para mostrar solo los vendedores que han facturado mas de 3000€.
    2- Agrupar los datos para calcular el total de ventas por region.

In [10]:
# sacr el dataframe e  imprimirlo por pantalla
datos = {
    'vendedor': ['Ana', 'Luis', 'Marta', 'Carlos', 'Elena'],
    'region': ['Norte', 'Sur', 'Este', 'Oeste', 'Norte'],
    'ventas': [2500, 3200, 4100,1500,3800]
}

df_ventas = pd.DataFrame(datos)
df_ventas

  vendedor region  ventas
0      Ana  Norte    2500
1     Luis    Sur    3200
2    Marta   Este    4100
3   Carlos  Oeste    1500
4    Elena  Norte    3800

1- filtrar ventas superiores a 3000€

In [11]:
ventas_mayor_3000 = df_ventas[df_ventas['ventas'] > 3000]
display('ventas > 3000', ventas_mayor_3000)

'ventas > 3000'

  vendedor region  ventas
1     Luis    Sur    3200
2    Marta   Este    4100
4    Elena  Norte    3800

In [12]:
ventas_entre_1000_2000 = df_ventas[(df_ventas['ventas'] > 1000) & (df_ventas['ventas']< 2000) ]
ventas_entre_1000_2000

  vendedor region  ventas
3   Carlos  Oeste    1500

# agrupar los datos y calcular el total de las ventas por region

In [13]:
ventas_por_region = df_ventas.groupby('region')['ventas'].sum()
ventas_por_region

region
Este     4100
Norte    6300
Oeste    1500
Sur      3200
Name: ventas, dtype: int64